name: Continuous integration

on:
  push:

jobs:
  continuousIntegration:
    name: Test Assimulo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check environment
        run: |
          pwd
          ls -la
          env
          python -c "import sys, sysconfig; print(sys.prefix); print (sys.path); print (sysconfig.get_paths())"

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install SUNDIALS
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends libsundials-dev

      - name: Install Python requirements
        run: |
          pip install -U pip==22.0.2
          pip install cython==0.29.28
          pip install scipy matplotlib
          pip install nose

      - name: Install Assimulo
        env:
          ASSIMULO_VERSION: 3.4.3
        run: |
          pip install --install-option="--optimize=1" \
            --install-option="--extra-fortran-link-flags=-shared" \
            --install-option="--sundials-home=/usr" \
            --install-option="--blas-home=/usr/lib/x86_64-linux-gnu" \
            --install-option="--lapack-home=/usr" \
            --install-option="--extra-fortran-compile-flags=-fallow-argument-mismatch"  \
            --install-option="--extra-c-flags=-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION" \
            git+https://github.com/modelon-community/Assimulo.git@Assimulo-${ASSIMULO_VERSION}

      - name: Test Assimulo
        run: python test_assimulo.py

      - name: Install and test PySCeS
        run: |
          pip install pysces
          python -c "import pysces; pysces.test(3)"
          python test_pysces.py
